version: '3'
services:
    apache:
        build: .docker/apache
        container_name: dev_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/test
        depends_on:
          - php

    mysql:
        image: mysql:5.7
        container_name: dev_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpass0
            MYSQL_DATABASE: devDB
            MYSQL_USER: dev
            MYSQL_PASSWORD: devpass
        ports:
            # On rend la BDD accessible depuis notre ordinateur pour le débug
            - 3306:3306

    php:
        build: .docker/php
        container_name: dev_php
        volumes:
          - .:/home/wwwroot/test
        depends_on:
          - mysql